### ISSUE TITLE
Path to run...

### ISSUE THREAD

**Issue by stdex** [fortharris/Pcode#14]
If i'm try to run python3 /opt/pcode/Pcode.py it's return:
Traceback (most recent call last):
  File "/opt/pcode/Pcode.py", line 275, in <module>
    main = Pcode()
  File "/opt/pcode/Pcode.py", line 38, in __init__
    self.useData = UseData()
  File "/opt/pcode/Extensions/UseData.py", line 327, in __init__
    file = open("settings.ini", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'settings.ini'

If i'm in /opt/pcode/ and call python3 Pcode.py pcode run sucess.

**Comment by fortharris** [comment]
You may have to change your directory to the Pcode directory before running it. Try it and let me know how it goes.
